name: My First Workflow


on:
- push


jobs: 

 my-first-workflow:

  runs-on: ubuntu-latest

  steps: 
  - name: echo the date
    run: echo "The current time and date in GitHub is $(date)"
  - name: echo information about the context
    run: echo "head_ref - ${{github.head_ref}}, owner - ${{github.repository_owner}}"